// <auto-generated />
using System;
using Cinemateque.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinemateque.DataAccess.Migrations
{
    [DbContext(typeof(CinematequeContext))]
    [Migration("20200516181851_movieModel")]
    partial class movieModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorName")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.ActorRatingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActorId");

                    b.Property<DateTime>("Date");

                    b.Property<double?>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("ActorRatingEntry");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Crew.CrewRatingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CrewMemberId");

                    b.Property<DateTime>("Date");

                    b.Property<double?>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("CrewRatingEntry");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.CrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmsChecked");

                    b.Property<string>("Job");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DirectorName")
                        .HasMaxLength(50);

                    b.Property<int>("FilmsChecked");

                    b.Property<double?>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DirectorId");

                    b.Property<double?>("Discount");

                    b.Property<string>("FilmName");

                    b.Property<string>("Genre");

                    b.Property<string>("Image");

                    b.Property<DateTime?>("PremiereDate");

                    b.Property<double?>("Price");

                    b.Property<int?>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.FilmActors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActorId");

                    b.Property<int?>("FilmId");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmActors");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.FilmReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date");

                    b.Property<int?>("FilmId");

                    b.Property<string>("RewardName");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmReward");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Movie.MovieDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActorsCsvs");

                    b.Property<string>("ActorsPopularity");

                    b.Property<double>("Budget");

                    b.Property<string>("Companies");

                    b.Property<string>("CrewCsvs");

                    b.Property<string>("CrewPopularity");

                    b.Property<string>("Genres");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FilmId");

                    b.Property<string>("Status")
                        .HasMaxLength(50);

                    b.Property<int>("UserId");

                    b.HasKey("OrderId");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Passwrod")
                        .HasMaxLength(30);

                    b.Property<int?>("Rating");

                    b.Property<string>("Role")
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.UserFilms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FilmId");

                    b.Property<float?>("Rating");

                    b.Property<string>("Status")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFilms");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.ActorRatingEntry", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.Actor", "Actor")
                        .WithMany("Ratings")
                        .HasForeignKey("ActorId");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Crew.CrewRatingEntry", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.CrewMember", "CrewMember")
                        .WithMany("Ratings")
                        .HasForeignKey("CrewMemberId");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Film", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.FilmActors", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.HasOne("Cinemateque.DataAccess.Models.Film", "Film")
                        .WithMany("FilmActors")
                        .HasForeignKey("FilmId");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.FilmReward", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.Film", "Film")
                        .WithMany("FilmReward")
                        .HasForeignKey("FilmId");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.Order", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.Film", "Film")
                        .WithMany("Order")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK_Order_Film");

                    b.HasOne("Cinemateque.DataAccess.Models.User", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Order_User");
                });

            modelBuilder.Entity("Cinemateque.DataAccess.Models.UserFilms", b =>
                {
                    b.HasOne("Cinemateque.DataAccess.Models.Film", "Film")
                        .WithMany("UserFilms")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK_UserFilms_Film");

                    b.HasOne("Cinemateque.DataAccess.Models.User", "User")
                        .WithMany("UserFilms")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserFilms_User");
                });
#pragma warning restore 612, 618
        }
    }
}
