// <auto-generated />
using System;
using Cinemateque.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinemateque.Migrations
{
    [DbContext(typeof(CinematequeContext))]
    partial class CinematequeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinemateque.Models.Actor", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(30);

                    b.Property<int?>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("Cinemateque.Models.Director", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("DirectorName")
                        .HasMaxLength(50);

                    b.Property<int?>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Director");
                });

            modelBuilder.Entity("Cinemateque.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DirectorId");

                    b.Property<string>("FilmName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Genre")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("Cinemateque.Models.FilmActors", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("ActorId");

                    b.Property<int?>("FilmId");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmActors");
                });

            modelBuilder.Entity("Cinemateque.Models.FilmReward", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FilmId");

                    b.Property<string>("RewardName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("FilmReward");
                });

            modelBuilder.Entity("Cinemateque.Models.User", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Passwrod")
                        .HasMaxLength(30);

                    b.Property<int?>("Rating");

                    b.Property<string>("Role")
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cinemateque.Models.UserFilms", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("FilmId");

                    b.Property<float?>("Rating");

                    b.Property<string>("Status")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFilms");
                });

            modelBuilder.Entity("Cinemateque.Models.Film", b =>
                {
                    b.HasOne("Cinemateque.Models.Director", "Director")
                        .WithMany("Film")
                        .HasForeignKey("DirectorId")
                        .HasConstraintName("FK_Film_Director");
                });

            modelBuilder.Entity("Cinemateque.Models.FilmActors", b =>
                {
                    b.HasOne("Cinemateque.Models.Actor", "Actor")
                        .WithMany("FilmActors")
                        .HasForeignKey("ActorId")
                        .HasConstraintName("FK_FilmActors_Actor");

                    b.HasOne("Cinemateque.Models.Film", "Film")
                        .WithMany("FilmActors")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK_FilmActors_Film");
                });

            modelBuilder.Entity("Cinemateque.Models.FilmReward", b =>
                {
                    b.HasOne("Cinemateque.Models.Film", "Film")
                        .WithMany("FilmReward")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK_FilmReward_Film1");
                });

            modelBuilder.Entity("Cinemateque.Models.UserFilms", b =>
                {
                    b.HasOne("Cinemateque.Models.Film", "Film")
                        .WithMany("UserFilms")
                        .HasForeignKey("FilmId")
                        .HasConstraintName("FK_UserFilms_Film");

                    b.HasOne("Cinemateque.Models.User", "User")
                        .WithMany("UserFilms")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserFilms_User");
                });
#pragma warning restore 612, 618
        }
    }
}
